version: 0.2
phases:
  install:
    commands:
     - yarn
  pre_build:
    commands:
      - yarn build
  build:
    commands:
      - echo run build command.
      - aws s3 sync ./public s3://${bucket_name} --delete --acl "public-read"
      - aws cloudfront create-invalidation --distribution-id ${cloudfront_distribution_id} --paths '/*'